spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: tenpo-group
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        cache: DEBUG
server:
  error:
    include-stacktrace: never
  port: 8091

percentage-api:
  base-path: ${PERCENTAGE_API_BASE_PATH}
  percentage-path: ${PERCENTAGE_PATH}

kafka:
  topic:
    name: history
